#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config window_gap           8

bspc config focused_border_color "#C97236"
bspc config normal_border_color  "#E3E3E3"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

