#:schema https://jj-vcs.github.io/jj/latest/config-schema.json

[user]
name = "Barry Chen"
email = "chenba@gmail.com"

[signing]
behavior = "own"
backend = "ssh"
key = "~/.ssh/id_rsa"

[ui]
editor = "nvim"
diff-editor = "gitpatch"
diff-in-editor = true

[merge-tools.gitpatch]
program = "sh"
edit-args = ["-c", '''
  set -eu
  rm -f "$right/JJ-INSTRUCTIONS"
  git -C "$left" init -q
  git -C "$left" add -A
  git -C "$left" commit -q -m baseline --allow-empty
  mv "$left/.git" "$right"
  git -C "$right" add --intent-to-add --ignore-removal .
  git -C "$right" add -p
  git -C "$right" diff-index --quiet --cached HEAD && { echo "No changes done, aborting split."; exit 1; }
  git -C "$right" commit -q -m split
  git -C "$right" reset -q --hard
''',
]

[remotes.origin]
auto-track-bookmarks = "glob:*"

[template-aliases]
'format_short_change_id(id)' = 'id.shortest()'

[aliases]
bk  = ["bookmark"]
dup = ["duplicate"]
gpb = ["git", "push", "-b"]
